<?php
/**
 * @ Author     : Apptha team
 * @copyright   : Copyright (c) 2011 (www.apptha.com)
 * @license     : http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
    $jq = jQuery.noConflict();
    $jq(function() {
        var dates = $jq( "#check-in, #check-out" ).datepicker({
            minDate: 0,
            dateFormat:'yy-mm-dd',
            numberOfMonths: 1,
            onSelect: function( selectedDate ) {
                var option = this.id == "check-in" ? "minDate" : "maxDate",
                instance = $jq( this ).data( "datepicker" ),
                date = $jq.datepicker.parseDate(
                instance.settings.dateFormat ||
                    $jq.datepicker._defaults.dateFormat,
                selectedDate, instance.settings );
                dates.not( this ).datepicker( "option", option, date );
            }
        });
    $jq('input[type=text], input[type=password], textarea').placeholder();
    });

</script>
<?php 
$countryCollection = $this->getCountries();
$cities = $this->getCities();
$cityCollection = $this->getCities();
if(Mage::getSingleton('cms/page')->getIdentifier() == 'home')
{
     Mage::getSingleton('core/session')->unsCity();
     Mage::getSingleton('core/session')->unsCheckIn();
     Mage::getSingleton('core/session')->unsCheckOutSearch();
}
$session = Mage::getSingleton('core/session');
?>
<div class="block block-search">
    <div class="block-title">
        <strong><span><?php echo $this->__('Search &amp; Book Hotels') ?></span></strong>
    </div>
    <div class="block-content">
    <form name="search-form" action="<?php echo $this->getUrl('reservation')?>"  method="get" id="search-form" >
        
        <div class="searchInputOl">
        <select name="city" id="city" class="validate-select" style="width:175px;">
        		<option value=""><?php echo $this->__('Select City'); ?></option>
                                <?php
                              foreach ($cities as $option) {
                                $value = $option['value'];
                                if($value != ''){
                                ?>
                                <option value="<?php echo $option['value'];?>" <?php if($session->getCity() == $option['value']){?> selected="selected" <?php }?>><?php echo $option['label'];?></option>
                                <?php }
                              }?>
                            </select>
        	
        </div>
          
        <div class="searchInputOl">
            <input type="text" name="check-in" id="check-in" class="search-input" placeholder="<?php echo $this->__('Check-In') ?>" value="<?php echo ($session->getCheckIn())?$session->getCheckIn():''?>"  />
        	<div id="cal1Container"></div>
        </div>
        
        <div class="searchInputOl">
        	<input type="text" name="check-out" id="check-out" class="search-input" placeholder="<?php echo $this->__('Check-Out') ?>" value="<?php echo ($session->getCheckOutSearch())?$session->getCheckOutSearch():''?>" />
        	<div id="cal2Container"></div>
        </div>
        <p class="seachButton">
        <button class="button" title="<?php echo $this->__('Search for hotels') ?>" type="submit"><span class=""><span><?php echo $this->__('Search for hotels'); ?></span></span></button>
        </p>
    </form>
    </div>
</div>
 <script type="text/javascript">
    //<![CDATA[
        var searchForm = new VarienForm('search-form', true);
    //]]>
    </script>
