<?php
/**
 * @ Author     : Apptha team
 * @copyright   : Copyright (c) 2011 (www.apptha.com)
 * @license     : http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
$categories = Mage::getModel('catalog/category')
        ->getCollection()
        ->addFieldToFilter('is_active', array("eq" => "1"));

if (Mage::getVersion() < '1.6.0.0') {
    if (count($categories) == 0) {
        ?>
        <div class="nav-container">
            <ul id="nav">
                <li class="level0 nav-1 level-top first firstmost last">
                    <a class="level-top" href="<?php echo Mage::getBaseUrl(); ?>"><?php echo $this->__('Home') ?></a>
                </li>
            </ul>
        </div>

    <?php } ?>
    <?php if (count($categories) >= 1) { ?>
        <script type="text/javascript">
            jQuery('.nav-container ul#nav').prepend('<li class="level0 nav-1 level-top first firstmost last"><a class="level-top" href="<?php echo Mage::getBaseUrl() ; ?>"><?php echo $this->__('Home') ?></a></li>');
        </script>
    <?php
    }
} else {

    if (count($categories) == 1) {
        ?>
        <div class="nav-container">
            <ul id="nav">
                <li class="level0 nav-1 level-top first firstmost last">
                    <a class="level-top" href="<?php echo Mage::getBaseUrl(); ?>"><?php echo $this->__('Home') ?></a>
                </li>
            </ul>
        </div>

    <?php } ?>
    <?php if (count($categories) >= 2) { ?>
        <script type="text/javascript">
            jQuery('.nav-container ul#nav').prepend('<li class="level0 nav-1 level-top first firstmost last"><a class="level-top" href="<?php echo Mage::getBaseUrl() ; ?>"><?php echo $this->__('Home') ?></a></li>');
        </script>
    <?php }
} ?>
