<?php
/**
 * Magento
 
 */
/* @var $this Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Price_Tier */
?>

<?php $_htmlId      = $this->getElement()->getHtmlId() ?>
<?php $_htmlClass   = $this->getElement()->getClass() ?>
<?php $_storeId		= $this->getProduct()->getStoreId() ?>
<?php $_htmlName    = $this->getElement()->getName() ?>
<?php $_readonly    = $this->getElement()->getReadonly() ?>
<?php $_multiWebsite= 0 && !Mage::app()->isSingleStoreMode();
?>

<tr>
    <td class="label"><?php echo $this->getElement()->getLabel() ?></td>
    <td colspan="10" class="grid roomtypes" style="position:static;">
    <table cellspacing="0" class="data border" id="roomtypes_table">
        <?php if (1||$_multiWebsite): ?>
        <col width="135" />
        <?php endif; ?>
        <col width="120" />
        <col width="260" />
        <?php if (!$_storeId): ?><col/><?php endif; ?>
        <col width="75" />
        <thead>
            <tr class="headings">
                <th <?php if (1 || !$_multiWebsite): ?>style="display:none"<?php endif; ?>><?php echo Mage::helper('sales')->__('Website') ?></th>
                <th><?php echo Mage::helper('catalog')->__('Room type') ?></th>
                <th style="display:none;"><?php echo Mage::helper('catalog')->__('Room type Id') ?></th>
                <th><?php echo Mage::helper('catalog')->__('Rooms available for deal') ?></th>                
                <th><?php echo Mage::helper('catalog')->__('Special Price') ?></th>
                <th style="display:none"><?php echo Mage::helper('catalog')->__('Status') ?></th>
                <th <?php if (!$_storeId): ?>style="display:none"<?php endif; ?>></th>
                <!--<th class="last"><?php echo Mage::helper('catalog')->__('Action') ?></th>-->
            </tr>
           <?php foreach ($this->getRoomTypes() as $_item): 
    		$dealData = $this->getDealValues($_item['id']);
    		$dealDataArray = $dealData->toArray();
    		?> 
            
            <?php endforeach;?>
           
        </thead>
        <tbody id="<?php echo $_htmlId ?>_container">
        <tr id="<?php echo $_htmlId ?>_add_template" class="template no-display">
                <td <?php if (1|| !$_multiWebsite): ?>style="display:none"<?php endif; ?>>
                <select disabled="no-template" class="<?php echo $_htmlClass ?> required-entry" name="<?php echo $_htmlName ?>[__index__][website_id]" id="deals_row___index___website">
                    <?php foreach ($this->getWebsites() as $_websiteId => $_info): ?>
                    <option value="<?php echo $_websiteId ?>"><?php echo $_info['name'] ?><?php if (!empty($_info['currency'])): ?> [<?php echo $_info['currency'] ?>]<?php endif; ?></option>
                    <?php endforeach ?>
                </select>
                
                </td>
					
                <td style="text-align:right;" disabled="no-template">
                	<input type="text" readonly name="<?php echo $_htmlName ?>[__index__][room_type_name]" id="deals_row___index___room_type_name" class="<?php echo $_htmlClass ?>" disabled="no-template" value="<?php echo $_item['room_type'] ?>">
                	
					
                </td>
                <td style="display:none;" disabled="no-template">
                	<input type="text" name="<?php echo $_htmlName ?>[__index__][room_type_id]" id="deals_row___index___room_type_id" class="<?php echo $_htmlClass ?>" value="<?php echo $_item['id'] ?>">
					
                </td>
                
                 <td style="text-align:right;" disabled="no-template">
					<input style="width:100px !IMPORTANT;" type="text" name="<?php echo $_htmlName ?>[__index__][rooms_for_deal]" id="deals_row___index___rooms_for_deal" class="<?php echo $_htmlClass ?>" value="<?php echo $dealDataArray['items'][0]['rooms_for_deal'];?>" />
                </td>
                
                 <td style="text-align:right;" disabled="no-template">
                 <?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();?>
					<input style="width:100px !IMPORTANT;" type="text" name="<?php echo $_htmlName ?>[__index__][deal_special_price]" id="deals_row___index___deal_special_price" class="<?php echo $_htmlClass ?>" value="<?php echo $dealDataArray['items'][0]['deal_special_price'];?>"/>
                </td>
                
                
                <?php
                //if(count($dealData) > 0){
                	if($dealDataArray['items'][0]['deal_status'] ==1)
                    	$select = 'selected="selected"';
	                else
	                	$select = '';
                //}
                
                 ?>
                
                <td >
					<select style="display:none" name="<?php echo $_htmlName ?>[__index__][deal_status]" id="deals_row___index___deal_status" class="<?php echo $_htmlClass ?> required-entry" disabled="no-template">
						<option value="0" <?php echo $select;?> >Disable</option>
						<option value="1" <?php echo $select;?> >Enable</option>
					</select>
                </td>
                
                <td <?php if (!$_storeId): ?>style="display:none"<?php endif; ?>>
					<input type="checkbox" name="<?php echo $_htmlName ?>[__index__][use_default_value]" id="deals_row___index___use_default_value"/> Use default value
                </td>
                

                
            </tr>
        </tbody>
    </table>
    
    <script type="text/javascript">
//<![CDATA[
    var dealsControl = {
        template : new Template('<tr>' + $('<?php echo $_htmlId ?>_add_template').innerHTML.replace(/__index__/g, '#{index}').replace(/ disabled="?no-template"?/g, '').replace(/ disabled/g, '').replace(/="'([^']*)'"/g, '="$1"') + '</tr>'),
        itemsCount : 0,
        defaultStoreId : <?php echo $_storeId;?>,
        deleteButton: false,
        addItem  : function () {
            <?php if($_readonly): ?>
            if (arguments.length < 5) {
                return;
            }
            <?php endif; ?>
            data = {};
            data.store_id = <?php echo $_storeId;?>;
            data.room_type_name = '';
            data.date = '';
            //data.period_dow = 1;
            data.index = this.itemsCount++;
            if(arguments.length >= 5) {
                data.store_id = parseInt(arguments[0]);
                data.room_type_name      = arguments[1];
                data.room_type_id      = arguments[2];
                data.rooms_for_deal      = arguments[3];
                data.deal_special_price      = arguments[4];
				
                data.deal_from        = arguments[5];
                data.deal_to        = arguments[6];
				data.deal_status = arguments[7]; 
            }
            $('<?php echo $_htmlId ?>_container').innerHtml = '';
            Element.insert($('<?php echo $_htmlId ?>_container'), {'bottom':this.template.evaluate(data)});
            $('deals_row_'+data.index+'_room_type_name').setValue(data.room_type_name);
            $('deals_row_'+data.index+'_website').setValue(data.website_id);
            $('deals_row_'+data.index+'_room_type_id').setValue(data.room_type_id);
            $('deals_row_'+data.index+'_rooms_for_deal').setValue(data.rooms_for_deal);
            $('deals_row_'+data.index+'_deal_special_price').setValue(data.deal_special_price);
            $('deals_row_'+data.index+'_deal_from').setValue(data.deal_from);
            $('deals_row_'+data.index+'_deal_to').setValue(data.deal_to);
            $('deals_row_'+data.index+'_deal_status').setValue(data.deal_status);
            
            $('deals_row_'+data.index+'_use_default_value').setValue(data.store_id == 0);
			if(data.store_id && (typeof arguments[8] == 'undefined')){
				$($('deals_row_'+data.index+'_use_default_value').parentNode).style.visibility='hidden';
			}

			$('deals_row_'+data.index+'_use_default_value').onclick = function(){
				if(this.checked){
					$(this.parentNode.parentNode).select('input', 'select', 'button')
						.each(dealsControl.disableElement);
				}else{
					$(this.parentNode.parentNode).select('input', 'select', 'button')
						.each(dealsControl.enableElement);
				}
			}

			if(!data.store_id && parseInt(this.defaultStoreId)){
				 $($('deals_row_'+data.index+'_use_default_value').parentNode.parentNode)
						.select('input', 'select', 'button')
						.each(dealsControl.disableElement);
						
			}
			
			
            
            <?php if ($_readonly): ?>
            $('<?php echo $_htmlId ?>_container').select('input', 'select')
                .each(this.disableElement);
            $('<?php echo $_htmlId ?>_container').up('table').select('button')
                .each(this.disableElement);
            <?php endif; ?>
            
        },
        disableElement: function(elem) {
            if(elem.type == 'checkbox') return;
            elem.disabled = true;
            elem.addClassName('disabled');
        },
        enableElement: function(elem) {
            elem.disabled = false
            elem.removeClassName('disabled');
        },       
        deleteItem : function(event) {
        }
    }
    
    <?php foreach ($this->getRoomTypes() as $_item): 
    		$dealData = $this->getDealValues($_item['id']);
    		$dealDataArray = $dealData->toArray();
    	$dow = new Zend_Date($dealDataArray['items'][0]['date_from'], 'Y-MM-dd');
    
		$_item['deal_from'] = ($dealDataArray['items'][0]['date_from']);
		$_item['deal_to'] = ($dealDataArray['items'][0]['date_to']);
		$_item['room_for_deal'] = $dealDataArray['items'][0]['rooms_for_deal'];
		$_item['deal_special_price'] = $dealDataArray['items'][0]['deal_special_price'];
		$_item['deal_status'] = $dealDataArray['items'][0]['deal_status'];
		
		$dow = $dow->toArray();
		//$dow = $dow['weekday'];
		
    ?>	
    dealsControl.addItem('<?php echo $_item['store_id'] ?>', '<?php echo $_item['room_type'] ?>', '<?php echo $_item['id'] ?>', '<?php echo $_item['room_for_deal'] ?>', '<?php echo $_item['deal_special_price'] ?>', '<?php echo $_item['deal_from']?>',  '<?php echo $_item['deal_to']?>', '<?php echo $_item['deal_status']?>', true);
    <?php endforeach; ?>
    <?php if ($_readonly): ?>
    $('<?php echo $_htmlId ?>_container').up('table').select('button')
        .each(excludedDaysControl.disableElement);
<?php endif; ?>
    
//]]>
	
	function fireChangeEvt(obj){
			
			if(typeof document.createEvent !== 'undefined'){
				var e = document.createEvent('HTMLEvents');
				e.initEvent('change', false, false);
				obj.dispatchEvent(e);
			}else{
				obj.fireEvent('onchange')
			}
		}
	</script>
    


</td>
</tr>

