<?php ?>
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head head-products">
        <?php echo Mage::helper('catalog')->__('Hotel Order(s)') ?>
        </h3></td>
        
    </tr>
</table>
</div>
<?php if( !$this->isSingleStoreMode() ): ?>
<?php echo $this->getChildHtml('store_switcher');?>
<?php endif;?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
