<?php
/**
 * @name         :  Apptha One Step Checkout
 * @version      :  1.7
 * @since        :  Magento 1.4
 * @author       :  Apptha - http://www.apptha.com
 * @copyright    :  Copyright (C) 2011 Powered by Apptha
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  June 20 2011
 * @Modified By  :  Bala G
 * @Modified Date:  August 1 2013
 *
 * */
?>
<?php
/* reurn as jsencode to the prototype js */
$data = array(
    'shipping_method' => $this->getChildHtml('shipping_method'),
    'payment_method' => $this->getChildHtml('payment_methods'),
    'product_information' => $this->getChildHtml('product-info')
);
echo Zend_Json::encode($data); ?>